name: Build and publish image

on:
  workflow_dispatch:
    inputs:
      steam-beta:
        description: 'Steam beta branch'
        required: true
        default: 'headless'
        type: choice
        options:
          - headless
          - prerelease

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    if: github.repository_owner == 'naborisk'
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: write .env file
        run: |
          touch .env
          echo STEAM_USER=${{ secrets.STEAM_USER }} >> .env
          echo STEAM_PASS=${{ secrets.STEAM_PASS }} >> .env
          echo BETA_PASSWORD=${{ secrets.BETA_PASSWORD }} >> .env
          echo STEAM_BETA=${{ github.event.inputs.steam-beta }} >> .env

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for build version extraction
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:temp

      - name: Extract build version
        run: |
          echo RESONITE_VERSION=$(docker run --entrypoint /bin/bash --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:temp -c "cat Build.version") >> $GITHUB_ENV

      - name: Print version
        run: echo ${{ env.RESONITE_VERSION }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable=${{ github.event.inputs.steam-beta == 'headless' }}
            type=raw,value=${{ env.RESONITE_VERSION }}
            type=raw,value=${{ github.event.inputs.steam-beta }}
            type=sha
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
